// client/src/views/EndQuiz.vue
<template>
  <section>
    <h2>That's it</h2>
    <p>Your score: You answered {{ score }} out of {{ number }} questions correctly.</p>
    <p>
      <router-link tag="button" to="/" class="button">Play again!</router-link>
    </p>
  </section>
</template>

<script>
  export default {
    name: 'EndQuiz',
    props: {
      score: {
        type: Number,
        required: true
      },
      number: {
        type: Number,
        required: true
      }
    }
  }
</script>

<style scoped>
    @import '../assets/button.css';
</style>

// src/app/end-quiz/end-quiz/end-quiz.component.ts
import { Component, OnInit } from '@angular/core';
import { HeadingService } from '../../shared/heading.service';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'quiz-end-quiz',
  templateUrl: './end-quiz.component.html',
  styleUrls: ['./end-quiz.component.css']
})
export class EndQuizComponent implements OnInit {

  score: string;
  numberOfQuestions: string;

  constructor(private headingService: HeadingService,
              private route: ActivatedRoute,
              private router: Router) { }

  ngOnInit() {
    this.headingService.emitChange('That\'s it!');
    this.route
        .params
        .subscribe((params: {score: string, numberOfQuestions: string}) => {
          this.score = params.score;
          this.numberOfQuestions = params.numberOfQuestions;
        });
  }

  playAgain() {
    this.router.navigate([`/start`], {relativeTo: this.route});
  }

}

<p>Your score: You answered {{ score }} out of {{ numberOfQuestions }} questions correctly.</p>

<p>
  <button (click)="playAgain()" class="button" type="button">Play again!</button>
</p>
